publish_mode: editorial_workflow
media_folder: "assets/uploads"

backend:
  name: git-gateway
  repo: https://github.com/sites-yari/editval-formacao-netlify
  branch: master # Branch to update (optional; defaults to master)
  site_domain: editvalue-capitalhumano.netlify.com

collections:
#====================| POSTS |===================================================|  
  #-----| Read me |------------------------------|
  - name: "posts"
    label: "Instruções"
    folder: "_posts"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Data de publicação", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Instruções", name: "body", widget: "markdown" }

  
